version: 2.1

orbs:
  node: circleci/node@latest

jobs:
  build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          packages: # Jest and Istanbul packages
            - jest
            - jest-junit
            - istanbul-lib-coverage
            - istanbul-lib-report
            - istanbul-reports
            - istanbul-api
            - istanbul-instrumenter-loader
      - run: yarn install # or npm install if you're using npm
      - run:
          name: Run tests with coverage
          command: yarn test --coverage
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

workflows:
  build_and_test:
    jobs:
      - build
