version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coverage
          command: |
            npm run test
            # Add your Firebase test command here
            npm run test:firebase
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build