version: 2.1

jobs:
  build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - run: npm install # or yarn install if you're using yarn
      - run:
          name: Run tests with coverage
          command: npm test -- --coverage
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

workflows:
  build_and_test:
    jobs:
      - build
